import { CallRecord, Lead, Meeting } from "@/types/crm";

export const initialLeads: Lead[] = [
  {
    id: "L-001",
    name: "Mariana Costa",
    company: "Vision Tech",
    phone: "(11) 98888-1010",
    status: "Novo",
    source: "Instagram",
    owner: "Rafael",
    email: "mariana@visiontech.com",
    notes: "Interessada em pacote trimestral.",
    channel: "inbound",
    city: "Sao Paulo - SP",
    niche: "Clinica de Estetica",
    entryDate: "2026-03-12",
    lastInteraction: "2026-03-26 10:20",
    nextAction: "Enviar proposta comercial ate 29/03",
    nextActionDate: "2026-03-29",
    temperature: "quente",
    history: [
      {
        id: "H-001-1",
        date: "2026-03-12",
        time: "09:10",
        eventType: "lead criado",
        description: "Lead entrou via formulario da campanha Meta Ads.",
        owner: "Rafael",
      },
      {
        id: "H-001-2",
        date: "2026-03-13",
        time: "11:40",
        eventType: "WhatsApp enviado",
        description: "Primeiro contato com roteiro de qualificacao.",
        owner: "Rafael",
      },
      {
        id: "H-001-3",
        date: "2026-03-18",
        time: "15:00",
        eventType: "reuniao agendada",
        description: "Reuniao de apresentacao marcada para sexta.",
        owner: "Rafael",
      },
      {
        id: "H-001-4",
        date: "2026-03-26",
        time: "10:20",
        eventType: "mudanca de status",
        description: "Lead movido para Proposta.",
        owner: "Rafael",
      },
    ],
    inboundQualification: {
      campaign: "Campanha Meta Conversao",
      mainInterest: "aumentar conversao",
      initialMessage: "Preciso responder mais rapido os contatos do Instagram.",
      businessType: "estetica",
      specialty: "Harmonizacao facial",
      monthlyRevenueRange: "R$ 120k a R$ 180k/mensal",
      averageLeadsPerMonth: "140",
      painPoints: ["demora no atendimento", "sem acompanhamento", "perde leads"],
      mainProblem: "Perde oportunidade por atraso no primeiro contato comercial.",
      decisionMakerIdentified: "sim",
      buyingMoment: "quer resolver",
      icpFit: "alto",
    },
    internalNotes: [],
    observationLog: [
      {
        id: "O-001-1",
        date: "2026-03-26",
        time: "10:22",
        owner: "Rafael",
        type: "follow-up",
        content: "Cliente pediu retorno apos alinhar valores com a equipe.",
      },
    ],
  },
  {
    id: "L-002",
    name: "Gustavo Lima",
    company: "Studio Prime",
    phone: "(21) 97777-2020",
    status: "Contato iniciado",
    source: "Indicacao",
    owner: "Camila",
    email: "gustavo@studioprime.com",
    notes: "Pediu reuniao de alinhamento comercial.",
    channel: "outbound",
    city: "Rio de Janeiro - RJ",
    niche: "Clinica Odontologica",
    entryDate: "2026-03-05",
    lastInteraction: "2026-03-25 16:10",
    nextAction: "Ligacao de follow-up em 28/03",
    nextActionDate: "2026-03-28",
    temperature: "morno",
    history: [
      {
        id: "H-002-1",
        date: "2026-03-05",
        time: "08:45",
        eventType: "lead importado",
        description: "Lead importado de lista de prospeccao outbound.",
        owner: "Camila",
      },
      {
        id: "H-002-2",
        date: "2026-03-08",
        time: "10:15",
        eventType: "ligacao realizada",
        description: "Ligacao inicial para entender operacao comercial.",
        owner: "Camila",
      },
      {
        id: "H-002-3",
        date: "2026-03-20",
        time: "14:30",
        eventType: "observacao interna",
        description: "Mostrou abertura para teste piloto de 30 dias.",
        owner: "Camila",
      },
      {
        id: "H-002-4",
        date: "2026-03-25",
        time: "16:10",
        eventType: "mudanca de status",
        description: "Lead atualizado para Em contato.",
        owner: "Camila",
      },
    ],
    outboundQualification: {
      decisionContacts: [{ name: "Gustavo Lima", phone: "(21) 97777-2020", email: "gustavo@studioprime.com" }],
      whoAnswered: "",
      attemptCount: "1",
      businessType: "odontologia",
      specialty: "Implantes",
      monthlyRevenueRange: "R$ 120k a R$ 180k/mensal",
      averageLeadsPerMonth: "95",
      employeeCountRange: "6-15",
      unitCount: "2",
      painPoints: ["agenda baguncada", "sem acompanhamento"],
      mainProblem: "Sem processo comercial padrao para retorno dos leads.",
      usesCrm: "nao",
      crmName: "",
      usesDigitalSchedule: "nao",
      usesSpreadsheet: "sim",
      usesNothing: "nao",
      decisionMakerIdentified: "sim",
      buyingMoment: "avaliando",
      icpFit: "alto",
      teamSize: "4",
    },
    internalNotes: [],
    observationLog: [],
  },
  {
    id: "L-003",
    name: "Fernanda Rocha",
    company: "Grupo Delta",
    phone: "(31) 96666-3030",
    status: "Proposta enviada",
    source: "Google Ads",
    owner: "Rafael",
    email: "fernanda@grupodelta.com",
    notes: "Avalia proposta com diretoria.",
    channel: "inbound",
    city: "Belo Horizonte - MG",
    niche: "Clinica de Fisioterapia",
    entryDate: "2026-03-10",
    lastInteraction: "2026-03-24 09:30",
    nextAction: "Reenviar proposta com opcao semestral",
    nextActionDate: "2026-03-30",
    temperature: "quente",
    history: [
      {
        id: "H-003-1",
        date: "2026-03-10",
        time: "12:05",
        eventType: "lead criado",
        description: "Lead capturado via landing page de conteudo.",
        owner: "Rafael",
      },
      {
        id: "H-003-2",
        date: "2026-03-11",
        time: "13:50",
        eventType: "WhatsApp enviado",
        description: "Mensagem com apresentacao inicial enviada.",
        owner: "Rafael",
      },
      {
        id: "H-003-3",
        date: "2026-03-19",
        time: "11:20",
        eventType: "proposta enviada",
        description: "Proposta comercial enviada por email.",
        owner: "Rafael",
      },
      {
        id: "H-003-4",
        date: "2026-03-24",
        time: "09:30",
        eventType: "observacao interna",
        description: "Diretoria pediu opcao de contrato semestral.",
        owner: "Rafael",
      },
    ],
    inboundQualification: {
      campaign: "Google Search - Agendamento",
      mainInterest: "automatizar atendimento",
      initialMessage: "Queremos centralizar WhatsApp e agenda em um unico fluxo.",
      businessType: "estetica",
      specialty: "Depilacao a laser",
      monthlyRevenueRange: "R$ 50k a R$ 120k/mensal",
      averageLeadsPerMonth: "110",
      painPoints: ["perde leads", "demora no atendimento"],
      mainProblem: "Equipe comercial perde timing no retorno e reduz conversao.",
      decisionMakerIdentified: "sim",
      buyingMoment: "avaliando",
      icpFit: "alto",
    },
    internalNotes: [],
    observationLog: [],
  },
  {
    id: "L-004",
    name: "Joao Nogueira",
    company: "Orbit Medical",
    phone: "(41) 95555-4040",
    status: "Qualificado",
    source: "Website",
    owner: "Iris",
    email: "joao@orbitmedical.com",
    notes: "Busca crescimento do outbound.",
    channel: "outbound",
    city: "Curitiba - PR",
    niche: "Clinica de Diagnostico",
    entryDate: "2026-03-01",
    lastInteraction: "2026-03-27 08:55",
    nextAction: "Apresentar plano de implantacao em 31/03",
    nextActionDate: "2026-03-31",
    temperature: "morno",
    history: [
      {
        id: "H-004-1",
        date: "2026-03-01",
        time: "09:00",
        eventType: "lead importado",
        description: "Conta enterprise adicionada via inteligencia comercial.",
        owner: "Iris",
      },
      {
        id: "H-004-2",
        date: "2026-03-04",
        time: "17:10",
        eventType: "ligacao realizada",
        description: "Ligacao com gerente de operacoes.",
        owner: "Iris",
      },
      {
        id: "H-004-3",
        date: "2026-03-16",
        time: "10:00",
        eventType: "reuniao agendada",
        description: "Demo tecnica agendada para o time comercial.",
        owner: "Iris",
      },
      {
        id: "H-004-4",
        date: "2026-03-27",
        time: "08:55",
        eventType: "mudanca de status",
        description: "Lead atualizado para Qualificado.",
        owner: "Iris",
      },
    ],
    outboundQualification: {
      decisionContacts: [],
      whoAnswered: "Recepcao central",
      attemptCount: "3",
      businessType: "odontologia",
      specialty: "Ortodontia",
      monthlyRevenueRange: "Acima de R$ 300k/mensal",
      averageLeadsPerMonth: "250+",
      employeeCountRange: "16-30",
      unitCount: "4+",
      painPoints: ["equipe desorganizada", "sem acompanhamento"],
      mainProblem: "Falta previsibilidade de follow-up e produtividade dos SDRs.",
      usesCrm: "sim",
      crmName: "Pipedrive",
      usesDigitalSchedule: "sim",
      usesSpreadsheet: "sim",
      usesNothing: "nao",
      decisionMakerIdentified: "nao",
      buyingMoment: "pesquisando",
      icpFit: "medio",
      teamSize: "9",
    },
    internalNotes: [],
    observationLog: [],
  },
];

export const initialMeetings: Meeting[] = [
  {
    id: "M-001",
    personName: "Mariana Costa",
    date: "2026-04-02",
    callTime: "09:30",
    reason: "apresentacao",
    owner: "Rafael",
    notes: "Apresentar plano de 90 dias para Vision Tech.",
  },
  {
    id: "M-002",
    personName: "Gustavo Lima",
    date: "2026-04-04",
    callTime: "14:00",
    reason: "acompanhamento",
    owner: "Camila",
    notes: "Revisar objecoes de orcamento.",
  },
  {
    id: "M-003",
    personName: "Fernanda Rocha",
    date: "2026-04-06",
    callTime: "11:00",
    reason: "fechamento",
    owner: "Iris",
    notes: "Negociar fechamento da proposta.",
  },
  {
    id: "M-004",
    personName: "Lucas Mendes",
    date: "2026-04-08",
    callTime: "10:00",
    reason: "apresentacao",
    owner: "Rafael",
    notes: "Apresentacao de escopo para operacao outbound.",
  },
  {
    id: "M-005",
    personName: "Patricia Alves",
    date: "2026-04-10",
    callTime: "16:00",
    reason: "acompanhamento",
    owner: "Camila",
    notes: "Acompanhar resultados da primeira semana.",
  },
  {
    id: "M-006",
    personName: "Renato Duarte",
    date: "2026-04-13",
    callTime: "09:00",
    reason: "fechamento",
    owner: "Iris",
    notes: "Fechamento de contrato trimestral.",
  },
  {
    id: "M-007",
    personName: "Aline Freitas",
    date: "2026-04-16",
    callTime: "13:30",
    reason: "apresentacao",
    owner: "Rafael",
    notes: "Apresentacao comercial inicial.",
  },
  {
    id: "M-008",
    personName: "Thiago Pires",
    date: "2026-04-19",
    callTime: "15:30",
    reason: "acompanhamento",
    owner: "Camila",
    notes: "Revisao de pendencias com diretoria.",
  },
  {
    id: "M-009",
    personName: "Bianca Torres",
    date: "2026-04-23",
    callTime: "11:30",
    reason: "fechamento",
    owner: "Iris",
    notes: "Alinhamento final para assinatura.",
  },
  {
    id: "M-010",
    personName: "Eduardo Silveira",
    date: "2026-04-27",
    callTime: "10:30",
    reason: "apresentacao",
    owner: "Rafael",
    notes: "Demonstracao de rotina de qualificacao.",
  },
  {
    id: "M-011",
    personName: "Juliana Braga",
    date: "2026-04-29",
    callTime: "17:00",
    reason: "acompanhamento",
    owner: "Camila",
    notes: "Ajustar cronograma de entregas.",
  },
  {
    id: "M-012",
    personName: "Carlos Matos",
    date: "2026-04-10",
    callTime: "11:00",
    reason: "apresentacao",
    owner: "Rafael",
    notes: "Apresentar proposta de onboarding.",
  },
  {
    id: "M-013",
    personName: "Helena Prado",
    date: "2026-04-23",
    callTime: "15:00",
    reason: "acompanhamento",
    owner: "Iris",
    notes: "Follow-up de pontos comerciais.",
  },
];

export const initialCalls: CallRecord[] = [
  {
    id: "C-001",
    leadId: "L-001",
    nome: "Mariana Costa",
    empresa: "Vision Tech",
    telefone: "(11) 98888-1010",
    data: "2026-03-28",
    inicio: "09:10",
    fim: "09:18",
    duracao: "08:00",
    status: "Atendida",
    observacao: "Ligacao de alinhamento inicial com interesse alto em demo.",
    origem: "Outbound",
    ultimoContatoTipo: "ligacao",
    startedAt: "2026-03-28T09:10:00-03:00",
    endedAt: "2026-03-28T09:18:00-03:00",
    durationSeconds: 480,
  },
  {
    id: "C-002",
    leadId: "L-002",
    nome: "Gustavo Lima",
    empresa: "Studio Prime",
    telefone: "(21) 97777-2020",
    data: "2026-03-28",
    inicio: "10:42",
    fim: "10:42",
    duracao: "00:00",
    status: "Nao atendida",
    observacao: "Sem retorno na primeira tentativa.",
    origem: "Outbound",
    ultimoContatoTipo: "ligacao",
    startedAt: "2026-03-28T10:42:00-03:00",
    endedAt: "2026-03-28T10:42:10-03:00",
    durationSeconds: 10,
  },
  {
    id: "C-003",
    leadId: "L-003",
    nome: "Fernanda Rocha",
    empresa: "Grupo Delta",
    telefone: "(31) 96666-3030",
    data: "2026-03-28",
    inicio: "11:25",
    fim: "11:32",
    duracao: "07:10",
    status: "Atendida",
    observacao: "Solicitou envio de proposta revisada ainda hoje.",
    origem: "Inbound",
    ultimoContatoTipo: "ligacao",
    startedAt: "2026-03-28T11:25:00-03:00",
    endedAt: "2026-03-28T11:32:10-03:00",
    durationSeconds: 430,
  },
  {
    id: "C-004",
    leadId: "L-004",
    nome: "Joao Nogueira",
    empresa: "Orbit Medical",
    telefone: "(41) 95555-4040",
    data: "2026-03-27",
    inicio: "14:00",
    fim: "14:00",
    duracao: "00:00",
    status: "Ocupado",
    observacao: "Linha ocupada; nova tentativa para o fim da tarde.",
    origem: "Outbound",
    ultimoContatoTipo: "ligacao",
    startedAt: "2026-03-27T14:00:00-03:00",
    endedAt: "2026-03-27T14:00:08-03:00",
    durationSeconds: 8,
  },
  {
    id: "C-005",
    nome: "Ana Ribeiro",
    empresa: "Clinica Alameda",
    telefone: "(19) 99111-1881",
    data: "2026-03-27",
    inicio: "15:18",
    fim: "15:29",
    duracao: "11:34",
    status: "Atendida",
    observacao: "Aprovou call de diagnostico para a proxima semana.",
    origem: "Inbound",
    ultimoContatoTipo: "ligacao",
    startedAt: "2026-03-27T15:18:00-03:00",
    endedAt: "2026-03-27T15:29:34-03:00",
    durationSeconds: 694,
  },
  {
    id: "C-006",
    nome: "Bruno Telles",
    empresa: "Prime Sorriso",
    telefone: "(48) 99822-4411",
    data: "2026-03-27",
    inicio: "16:45",
    fim: "16:46",
    duracao: "00:41",
    status: "Cancelada",
    observacao: "Cliente pediu para remarcar por conflito de agenda.",
    origem: "Outbound",
    ultimoContatoTipo: "ligacao",
    startedAt: "2026-03-27T16:45:00-03:00",
    endedAt: "2026-03-27T16:45:41-03:00",
    durationSeconds: 41,
  },
  {
    id: "C-007",
    nome: "Carla Menezes",
    empresa: "Life Odonto",
    telefone: "(62) 99334-2002",
    data: "2026-03-26",
    inicio: "09:55",
    fim: "10:03",
    duracao: "08:12",
    status: "Atendida",
    observacao: "Interesse em automacao de follow-up.",
    origem: "Inbound",
    ultimoContatoTipo: "ligacao",
    startedAt: "2026-03-26T09:55:00-03:00",
    endedAt: "2026-03-26T10:03:12-03:00",
    durationSeconds: 492,
  },
  {
    id: "C-008",
    nome: "Diego Salles",
    empresa: "Nova Clin",
    telefone: "(85) 98765-3001",
    data: "2026-03-26",
    inicio: "11:40",
    fim: "11:40",
    duracao: "00:00",
    status: "Nao atendida",
    observacao: "Sem resposta apos 3 toques.",
    origem: "Outbound",
    ultimoContatoTipo: "ligacao",
    startedAt: "2026-03-26T11:40:00-03:00",
    endedAt: "2026-03-26T11:40:10-03:00",
    durationSeconds: 10,
  },
  {
    id: "C-009",
    nome: "Elisa Prado",
    empresa: "Instituto Serena",
    telefone: "(27) 99991-3200",
    data: "2026-03-25",
    inicio: "13:20",
    fim: "13:25",
    duracao: "05:08",
    status: "Atendida",
    observacao: "Solicitou proposta com plano semestral.",
    origem: "Inbound",
    ultimoContatoTipo: "ligacao",
    startedAt: "2026-03-25T13:20:00-03:00",
    endedAt: "2026-03-25T13:25:08-03:00",
    durationSeconds: 308,
  },
  {
    id: "C-010",
    nome: "Fabio Cruz",
    empresa: "Atlas Med",
    telefone: "(51) 99222-7878",
    data: "2026-03-25",
    inicio: "15:05",
    fim: "15:06",
    duracao: "01:03",
    status: "Ocupado",
    observacao: "Linha ocupada no horario comercial.",
    origem: "Outbound",
    ultimoContatoTipo: "ligacao",
    startedAt: "2026-03-25T15:05:00-03:00",
    endedAt: "2026-03-25T15:06:03-03:00",
    durationSeconds: 63,
  },
  {
    id: "C-011",
    nome: "Gabriela Luz",
    empresa: "OnCare",
    telefone: "(71) 99666-8181",
    data: "2026-03-24",
    inicio: "10:11",
    fim: "10:19",
    duracao: "08:45",
    status: "Atendida",
    observacao: "Confirmou interesse em iniciar onboarding no proximo mes.",
    origem: "Inbound",
    ultimoContatoTipo: "ligacao",
    startedAt: "2026-03-24T10:11:00-03:00",
    endedAt: "2026-03-24T10:19:45-03:00",
    durationSeconds: 525,
  },
  {
    id: "C-012",
    nome: "Henrique Mota",
    empresa: "Clinica Aurora",
    telefone: "(61) 99555-4545",
    data: "2026-03-24",
    inicio: "17:40",
    fim: "17:40",
    duracao: "00:00",
    status: "Cancelada",
    observacao: "Ligacao cancelada por indisponibilidade do decisor.",
    origem: "Outbound",
    ultimoContatoTipo: "ligacao",
    startedAt: "2026-03-24T17:40:00-03:00",
    endedAt: "2026-03-24T17:40:03-03:00",
    durationSeconds: 3,
  },
];
